# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: comment out conflicting port 5912 from /etc/services
  replace:
    path: /etc/services
    regexp: '^([a-z\-]+\s+5912/.*)'
    replace: '# \1'

# DB2 fails to install on SLES 15 unless the bin user and group are added. The following tasks
# add the bin user and group to match SLES 12. See:
# https://www.ibm.com/support/pages/db2-luw-product-installation-fails-unix-platform-without-bin-user
- block:
  - name: add bin group
    group:
      name: bin
      gid: 1
  - name: add bin user
    user:
      name: bin
      group: bin
      home: /bin
      shell: /bin/bash
      uid: 1
  when:
  - ansible_os_family == 'Suse'
  - ansible_distribution_major_version == '15'
