# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is intended to be run twice: the first time with local_interface_state
# set to 'present', and the second time with it set to 'absent' to undo the change.

- name: ensure ansible state directory exists
  file:
    path: '{{ local_interface_ansible_state_dir }}'
    state: directory

- name: add ip to local interface
  command: ip addr add {{ local_interface_ip }}/{{ local_interface_netmask }} dev {{ local_interface_link }}
  register: local_interface_add
  failed_when: >-
    local_interface_add is failed and
    'RTNETLINK answers: File exists' not in local_interface_add.stderr
  when: local_interface_state == 'present'
  args:
    # This file is actually created by the 'create state file' task.
    creates: '{{ local_interface_ansible_state_dir }}/add-ip-to-local-interface'

- name: remove ip from local interface
  command: ip addr del {{ local_interface_ip }}/{{ local_interface_netmask }} dev {{ local_interface_link }}
  register: local_interface_rm
  failed_when: >-
    local_interface_rm is failed and
    'RTNETLINK answers: Cannot assign requested address' not in local_interface_rm.stderr
  when: local_interface_state == 'absent'
  args:
    creates: '{{ local_interface_ansible_state_dir }}/add-ip-to-local-interface'

- name: store ansible state
  copy:
    dest: '{{ local_interface_ansible_state_dir }}/add-ip-to-local-interface'
    content: ''
  when: local_interface_state == 'absent'
