# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: setup for real instance:
# - enable "delegated" driver
# - configure platform name in ~/.ssh/config, example:
#   Host test-hana
#     HostName 108.59.83.6
#     IdentityFile ~/.ssh/google_compute_engine
#     User johnmitchell
#
# NOTE: setup for fast local container:
# - enable "docker" driver

---
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: ssh
platforms:
  - name: test-hana

provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint -p .
