# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Windows bastion deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_project_path: ./tf
      sap_ansible_is_push_mode: false
      sap_state: '{{ state | default("present") }}'
      sap_tf_variables:
        instance_name: '{{ sap_win_instance_name }}'
        project_id: '{{ sap_project_id }}'
        source_image_family: '{{ sap_source_image_family }}'
        source_image_project: '{{ sap_source_image_project }}'
        subnetwork: '{{ sap_subnetwork }}'
        service_account_email: '{{ sap_win_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_win_service_account_name | default("sap-common-sa"), sap_project_id)) }}'
        subnetwork_project: '{{ sap_subnetwork_project_id | default(sap_project_id) }}'
        zone: '{{ sap_zone | default("us-central1-a") }}'
        instance_type: '{{ sap_win_instance_type | default("e2-standard-2") }}'
        autodelete_disk: '{{ sap_win_autodelete_boot_disk | default(true) }}'
        boot_disk_size: '{{ sap_win_boot_disk_size | default(50) }}'
        boot_disk_type: '{{ sap_win_boot_disk_type | default("pd-ssd") }}'
        network_tags: '{{ sap_win_network_tags | default([sap_network_tag | default("sap-allow-all")]) }}'
        use_public_ip: '{{ sap_win_use_public_ip | default(true) | bool }}'
        install_files_bucket_folder: '{{ sap_win_install_files_bucket_folder | default("sap-deployment-media/Windows-Bastion") }}'
