# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install packages
  package:
    name: python2-pyasn1-modules
    state: present
  register: result
  retries: 50
  until: result is succeeded
  delay: 10
  when: |
    ansible_os_family == 'Suse'

- name: Install required python package from GCE storage client
  pip:
    name: pyasn1-modules
    state: latest

# - name: Download GCE Storage Client
#   get_url: 
#     url: 'https://storage.googleapis.com/sapdeploy/gceStorageClient/gceStorageClient.py'
#     dest: '{{ sap_hana_gce_storage_client_path }}'
#     mode: 755
#   register: gce_storage_client_file

- name: Download GCE Storage Client
  get_url: 
    url: 'https://storage.googleapis.com/cloudsapdeploy/gcestorageclient/{{ gce_storage_client_package }}'
    dest: /tmp/
    mode: 775
  register: gce_storage_client_file

- name: Ensure gce storage client is installed for Suse
  zypper:
    name: '/tmp/{{ gce_storage_client_package }}'
    state: present
    disable_gpg_check: yes
  when: ansible_os_family == 'Suse'
  register: gce_storage_client_install
  until: gce_storage_client_install is succeeded
  retries: 30
  delay: 10

- name: Ensure gce storage client is installed for Redhat
  yum:
    name: '/tmp/{{ gce_storage_client_package }}'
    state: present
  when: ansible_os_family == 'RedHat'
  register: gce_storage_client_install
  until: gce_storage_client_install is succeeded
  retries: 30
  delay: 10

- name: 'Create {{ sap_hana_shared_mountpoint }}/gceStorageClient directory'
  file:
    path: '{{ sap_hana_shared_mountpoint }}/gceStorageClient'
    state: directory

- name: 'Check {{ sap_hana_usr_mountpoint }}/google-sapgcestorageclient/gceStorageClient.py exists'
  stat:
    path: '{{ sap_hana_usr_mountpoint }}/google-sapgcestorageclient/gceStorageClient.py'
  register: gce_storage_client_py

- name: 'Copy {{ sap_hana_usr_mountpoint }}/google-sapgcestorageclient/gceStorageClient.py to {{ sap_hana_shared_mountpoint }}/gceStorageClient directory'
  copy:
    src: '{{ sap_hana_usr_mountpoint }}/google-sapgcestorageclient/gceStorageClient.py'
    dest: '{{ sap_hana_shared_mountpoint }}/gceStorageClient/gceStorageClient.py'
    remote_src: yes
  when: gce_storage_client_py.stat.exists

- name: Create gcloud directory under sidadm user home directory
  file:
    path: '{{ sap_hana_usr_mountpoint }}/{{ sap_hana_sid }}/home/.config/gcloud/'
    state: directory
    owner: '{{ sap_hana_system_uid }}'
    group: '{{ sap_sapsys_gid }}'
    recurse: true

- name: Updating /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    line: '{{ item }}'
  with_items:
    - '{{ sap_hana_user }} ALL=NOPASSWD: /sbin/multipath,/sbin/multipathd,/etc/init.d/multipathd,/usr/bin/sg_persist,/bin/mount,/bin/umount,/bin/kill,/usr/bin/lsof,/usr/bin/systemctl,/usr/sbin/lsof,/usr/sbin/xfs_repair,/usr/bin/mkdir,/sbin/vgscan,/sbin/pvscan,/sbin/lvscan,/sbin/vgchange,/sbin/lvdisplay,/usr/bin/gcloud'
    - ''
