# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# These should be toggled to true in the inventory for relevant hosts.
sap_is_aas: false
sap_is_ascs: false
sap_is_db2: false
sap_is_db2_primary: false
sap_is_db2_secondary: false
sap_is_ers: false
sap_is_pas: false
sap_is_scs: false

hosts_file_entries:
- ip: '{{ sap_db2_vip }}'
  names: ['{{ sap_db2_virtual_host }}']
- ip: '{{ sap_nw_ascs_vip }}'
  names: ['{{ sap_nw_ascs_virtual_host }}']
- ip: '{{ sap_nw_ers_vip }}'
  names: ['{{ sap_nw_ers_virtual_host }}']

sap_db2_primary_ip: '{{
  hostvars.values()
  | selectattr("sap_is_db2_primary", "defined")
  | selectattr("sap_is_db2_primary")
  | map(attribute="ansible_default_ipv4.address")
  | list
  | first
}}'
sap_db2_secondary_ip: '{{
  hostvars.values()
  | selectattr("sap_is_db2_secondary", "defined")
  | selectattr("sap_is_db2_secondary")
  | map(attribute="ansible_default_ipv4.address")
  | list
  | first
}}'
sap_nw_ascs_instance_name: '{{
  hostvars.values()
  | selectattr("sap_is_ascs", "defined")
  | selectattr("sap_is_ascs")
  | map(attribute="ansible_hostname")
  | list
  | first
}}'
sap_nw_ascs_private_ip: '{{
  hostvars.values()
  | selectattr("sap_is_ascs", "defined")
  | selectattr("sap_is_ascs")
  | map(attribute="ansible_default_ipv4.address")
  | list
  | first
}}'
sap_nw_ers_instance_name: '{{
  hostvars.values()
  | selectattr("sap_is_ers", "defined")
  | selectattr("sap_is_ers")
  | map(attribute="ansible_hostname")
  | list
  | first
}}'
sap_nw_pas_instance_name: '{{
  hostvars.values()
  | selectattr("sap_is_pas", "defined")
  | selectattr("sap_is_pas")
  | map(attribute="ansible_hostname")
  | list
  | first
}}'
sap_nw_pas_virtual_host: '{{ sap_nw_pas_instance_name }}'

sap_db2_hadr_port1: 5951
sap_db2_hadr_port2: 5952
sap_db2_user: 'db2{{ sap_nw_sid | lower }}'
sap_db2_group: 'db{{ sap_nw_sid | lower }}adm'
sap_db2_state_dir: /db2/{{ sap_db2_user }}/.ansible-state

sap_nw_master_password: '{{ sap_nw_password }}'
sap_nw_sapadm_password: '{{ sap_nw_password }}'
sap_nw_sapsid_password: '{{ sap_nw_password }}'
sap_nw_sidadm_password: '{{ sap_nw_password }}'
sap_db2_dbsid_password: '{{ sap_nw_password }}'
sap_nw_cluster_user_password: '{{ sap_nw_password }}'
sap_nw_user: '{{ sap_nw_sid | lower }}adm'

sap_db2_sysadm_gid: 2002
sap_db2_sysctrl_gid: 2003
sap_db2_sysmaint_gid: 2004
sap_db2_sysmon_gid: 2005
sap_sapsys_gid: 2626
sap_nw_sidadm_uid: 2000
sap_nw_sapadm_uid: 2001
sap_nw_sapsid_uid: 2002
sap_db2_dbsid_uid: 2003

sap_scs_name: ASCS

sap_nw_ascs_instance_number: '00'
sap_nw_ers_instance_number: '10'
sap_nw_pas_instance_number: '00'
sap_nw_install_files_dest: /sapmnt/Software
sap_nw_kernel_files: '{{ sap_nw_install_files_dest }}/Kernel_Files'
sap_nw_rdbms_files: '{{ sap_nw_install_files_dest }}/RDBMS'

sap_nw_ascs_install_gateway: false
sap_nw_ascs_install_web_dispatcher: false

sap_nw_disks:
- name: usrsap
  partition_path : usrsap
- name: swap
  partition_path : swap
sap_nw_logvols:
  usrsap:
    size: 100%VG
    vol: usrsap
    mountpoint: /usr/sap
  swap:
    size: 100%VG
    vol: swap
    fstype: swap
    mountpoint: none
sap_nw_disks_aas: '{{ sap_nw_disks }}'
sap_nw_logvols_aas: '{{ sap_nw_logvols }}'
sap_nw_disks_ascs: '{{ sap_nw_disks }}'
sap_nw_logvols_ascs: '{{ sap_nw_logvols }}'
sap_nw_disks_db2: '{{ sap_nw_disks + [{ "name": "db2", "partition_path": "db2" }] }}'
sap_nw_logvols_db2: '{{ sap_nw_logvols | combine({ "db2": { "size": "100%VG", "vol": "db2", "mountpoint": "/db2" } }) }}'
sap_nw_disks_ers: '{{ sap_nw_disks }}'
sap_nw_logvols_ers: '{{ sap_nw_logvols }}'
sap_nw_disks_pas: '{{ sap_nw_disks }}'
sap_nw_logvols_pas: '{{ sap_nw_logvols }}'

# Defaults for using Cloud Filestore. Only sap_nw_nfs_server needs to be defined
# in variables if it is used.
sap_nw_nfs_server: ''
sap_nw_nfs_share: /sap
sap_nw_nfs_src: '{{ sap_nw_nfs_server }}:{{ sap_nw_nfs_share }}'
# _sap_nw_nfs_src is ony defined here for internal use. It is needed to make both AWX and
# non-AWX deployments work. AWX always defines both sap_nw_nfs_server and sap_nw_nfs_src;
# when one is set by the user, the other will be an empty string. When not using AWX, just
# one of sap_nw_nfs_server or sap_nw_nfs_src can be defined in vars.
_sap_nw_nfs_src: '{{ sap_nw_nfs_src if sap_nw_nfs_src != "" else sap_nw_nfs_server ~ ":" ~ sap_nw_nfs_share }}'

# If the condition below is true, source directories will be created under sap_nw_nfs_src.
# If it is false, it means neither sap_nw_nfs_server or sap_nw_nfs_src have been changed from
# the defaults. In that case, directories will not be created and sap_nw_*_nfs_mount_src
# variables must be defined instead.
sap_nw_create_nfs_source_dirs: '{{ _sap_nw_nfs_src != ":" ~ sap_nw_nfs_share }}'

# Default values to fill in sap_nw_nfsvols when one of sap_nw_nfs_server or sap_nw_nfs_src is defined.
# If not using default values, the sap_nw_*_nfs_mount_src variables can be defined individually.
sap_nw_sapmnt_nfs_mount_src: '{{ _sap_nw_nfs_src }}/sapmnt'
sap_nw_saptrans_nfs_mount_src: '{{ _sap_nw_nfs_src }}/saptrans'
sap_nw_ascs_nfs_mount_src: '{{ _sap_nw_nfs_src }}/ASCS{{ sap_nw_ascs_instance_number }}'
sap_nw_ascs_nfs_mount_dest: '/usr/sap/{{ sap_nw_sid }}/ASCS{{ sap_nw_ascs_instance_number }}'
sap_nw_ers_nfs_mount_src: '{{ _sap_nw_nfs_src }}/ERS{{ sap_nw_ers_instance_number }}'
sap_nw_ers_nfs_mount_dest: '/usr/sap/{{ sap_nw_sid }}/ERS{{ sap_nw_ers_instance_number }}'
sap_nw_nfsvols_aas:
- source: '{{ sap_nw_sapmnt_nfs_mount_src }}'
  mountpoint: /sapmnt
- source: '{{ sap_nw_saptrans_nfs_mount_src }}'
  mountpoint: /usr/sap/trans
sap_nw_nfsvols_db2:
- source: '{{ sap_nw_sapmnt_nfs_mount_src }}'
  mountpoint: /sapmnt
sap_nw_nfsvols_pas:
- source: '{{ sap_nw_sapmnt_nfs_mount_src }}'
  mountpoint: /sapmnt
- source: '{{ sap_nw_saptrans_nfs_mount_src }}'
  mountpoint: /usr/sap/trans
sap_nw_nfsvols_scs:
- source: '{{ sap_nw_sapmnt_nfs_mount_src }}'
  mountpoint: /sapmnt
- source: '{{ sap_nw_saptrans_nfs_mount_src }}'
  mountpoint: /usr/sap/trans
- source: '{{ sap_nw_ascs_nfs_mount_src }}'
  mountpoint: '{{ sap_nw_ascs_nfs_mount_dest }}'
  owner: '{{ sap_nw_sidadm_uid }}'
  group: '{{ sap_sapsys_gid }}'
- source: '{{ sap_nw_ers_nfs_mount_src }}'
  mountpoint: '{{ sap_nw_ers_nfs_mount_dest }}'
  owner: '{{ sap_nw_sidadm_uid }}'
  group: '{{ sap_sapsys_gid }}'

sap_db2_product: 'DB2'
sap_db2_product_version: '11.5MP5FP1'
sap_db2_product_and_version: '{{ sap_db2_product }}/{{ sap_db2_product_version }}'
sap_nw_product: 'NetWeaver'
sap_nw_product_version: '750'
sap_nw_product_and_version: '{{ sap_nw_product }}/{{ sap_nw_product_version }}'
sap_product_vars:
  'NetWeaver/750':
    aas_product_id: 'NW_DI:NW750.DB6.ABAPHA'
    ascs_product_id: 'NW_ABAP_ASCS:NW750.DB6.ABAPHA'
    # Use distributed instead of HA product ID for DB2.
    db_product_id: 'NW_ABAP_DB:NW750.DB6.ABAP'
    dbcopy_product_id: 'NW_ABAP_DB:NW750.DB6.CP'
    ers_product_id: 'NW_ERS:NW750.DB6.ABAPHA'
    pas_product_id: 'NW_ABAP_CI:NW750.DB6.ABAPHA'
    swpm_path: '{{ sap_nw_install_files_dest }}/SWPM1.0'
    load_files: '{{ sap_nw_install_files_dest }}/NW75'
    install_files: [Kernel_Files, NW75, SWPM1.0]
    ensa_version: '1'
  'DB2/10.5FP9':
    db_client: '{{ sap_nw_install_files_dest }}/DB_CLIENT'
    install_files: [DB_CLIENT, RDBMS]
  'DB2/11.1MP4FP6':
    db_client: '{{ sap_nw_install_files_dest }}/DB_CLIENT'
    install_files: [DB_CLIENT, RDBMS]
  'DB2/11.5MP5FP1':
    db_client: '{{ sap_nw_install_files_dest }}/DB_CLIENT'
    install_files: [DB_CLIENT, RDBMS]
