# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Define install file name
  set_fact:
    sap_hana_install_file_name: '{{ sap_product_vars[sap_product_and_version].sap_hana_install_file_name }}'

- name: Define upgrade file name
  set_fact:
    sap_hana_upgrade_file_name: '{{ sap_product_vars[sap_product_and_version].sap_hana_upgrade_file_name }}'

- name: Create temporary directory to store the processed template
  tempfile:
    state: directory
    suffix: hanaconfig
  register: tmpdir

- name: Create .deploy directory
  file:
    path: /root/.deploy
    state: directory
    mode: 0775

- name: Deploy HANA Configfile Template for scaleout with standby
  template:
    src: "{{ role_path }}/templates/configfile-soby.j2"
    dest: "/root/.deploy/configfile.cfg"
    mode: 0750
  register: cftemplat

- name: Identify EXE archive install file
  find: 
    paths: "{{ sap_hostagent_rpm_remote_path }}"
    patterns: "*_part1.exe"
  register: exe_install_file

- name: Identify IMDB SAR archive install file
  find: 
    paths: "{{ sap_hostagent_rpm_remote_path }}"
    patterns: "*.SAR"
  register: sar_install_file

- name: Download unrar for unzipping hana
  get_url: 
    url: https://storage.googleapis.com/sapdeploy/dm-templates/third_party/unrar/unrar
    dest: /usr/bin
    mode: 0775
  when: ((exe_install_file.matched > 0) and (ansible_os_family == "RedHat"))

- name: Extract EXE Archive
  shell: |
    /usr/bin/unrar -o+ x "{{ item.path }}" 
  args:
    chdir: "{{ sap_hostagent_rpm_remote_path }}"
    creates: "{{ item.path.split('_')[0] }}/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm"
  register: sap_hana_deployment_register_extractexe
  with_items: "{{ exe_install_file.files }}"
  when: exe_install_file.matched > 0

- name: Check availability of "{{ item.path.split('_')[0] }}/DATA_UNITS/HDB_SERVER_LINUX_X86_64/hdblcm"
  stat:
    path: "{{ item.path.split('_')[0] }}/DATA_UNITS/HDB_SERVER_LINUX_X86_64/hdblcm"
  register: sap_hana_deployment_register_hdblcm_stat
  with_items: "{{ exe_install_file.files }}"
  when: exe_install_file.matched > 0

- name: Check if another instance of HANA DB is running with sid "{{ sap_hana_sid }}"
  stat:
    path: "/hana/shared/{{ sap_hana_sid }}"
  register: hana_db_running
  when: exe_install_file.matched > 0
