# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include copy ssh keys role
  include_role:
    name: sap-hana-copy-ssh-keys

- name: Create {{ sap_hana_sid }} directories in /hana/data and /hana/log
  file:
    path: "{{ item }}/{{ sap_hana_sid }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ sap_hana_data_mountpoint }}"
    - "{{ sap_hana_log_mountpoint }}"

- name: 'Create {{ sap_hana_shared_mountpoint }} and {{ sap_hana_backup_mountpoint }}'
  file:
    path: '{{ item }}'
    state: directory
    recurse: true
    mode: 0775
  with_items:
    - '{{ sap_hana_shared_mountpoint }}'
    - '{{ sap_hana_backup_mountpoint }}'

- name: 'Mount {{ sap_hana_shared_mountpoint }} and {{ sap_hana_backup_mountpoint }} filestore volumes'
  mount:
    src: '{{ item.source }}'
    path: '{{ item.path }}'
    state: mounted
    fstype: nfs
  loop:
    - { source: '{{ sap_hana_shared_fs_mount_point }}', path: '{{ sap_hana_shared_mountpoint }}' }
    - { source: '{{ sap_hana_backup_fs_mount_point }}', path: '{{ sap_hana_backup_mountpoint }}' }

- name: Install required python package from GCE storage client
  pip:
    name: pyasn1-modules
    state: latest

- name: Include gceStorageClient role
  include_tasks:
    file: gcestorageclient.yml
  vars:
    gce_storage_client_package: gceStorageClient.py

- name: 'Remove {{ sap_hana_gce_storage_client_path }}/gceStorageClient.pyc'
  file:
    path: '{{ sap_hana_gce_storage_client_path }}/gceStorageClient.pyc'
    state: absent

- name: 'Change {{ sap_hana_gce_storage_client_path }}/gceStorageClient.py permissions'
  file:
    path: '{{ sap_hana_gce_storage_client_path }}/gceStorageClient.py'
    mode: 0775
