# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include base role
  include_role:
    name: base

- name: Include storage role
  include_role:
    name: storage
  vars:
    disks: "{{ sap_hana_disks }}"
    logvols: "{{ sap_hana_logvols }}"

- name: Include hana packages download role
  include_role:
    name: sap-hana-download-packages

- name: Include sap pre-configure role
  include_role:
    name: sap-preconfigure
  when:
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version | int < 8

- name: Include sap hana pre-configure role
  include_role:
    name: sap-hana-preconfigure
  when: ansible_os_family == "RedHat"

- name: Include sap hana install role
  include_role:
    name: sap-hana-install

- name: Include sap hana start role
  include_role:
    name: sap-hana-start

- name: Include SAP hostagent install role
  include_role:
    name: sap-hostagent

- name: Include sap hana ssfs copy keys role
  include_role:
    name: sap-hana-ssfs-keys

- name: Include sap hana backup config role
  include_role:
    name: sap-hana-config-backup

- name: Include sap hana hdb user create role
  include_role:
    name: sap-hana-hdb-user

- name: Include sap hana hdb userstore role
  include_role:
    name: sap-hana-hdb-userstore
  vars:
    hdb_us_become_user: '{{ sap_hana_user }}'
    hdb_us_db_host: localhost
    hdb_us_db_password: '{{ sap_hana_db_system_password }}'
    hdb_us_db_port: '3{{ sap_hana_instance_number }}15'
    hdb_us_db_user: '{{ sap_hana_monitoring_user }}'
    hdb_us_key: '{{ sap_hana_user_store_key }}'
    hdb_us_source_file: '/usr/sap/{{ sap_hana_user }}/home/.sapenv.sh'

- name: Include sap hana backup role
  include_role:
    name: sap-hana-backup

- name: Include sap hana hsr config role
  include_role:
    name: sap-hana-hsr

- name: Include pacemaker install/config role
  include_role:
    name: pacemaker-hana
  vars:
    sap_cluster_user_password: '{{ sap_hana_cluster_user_password }}'

- name: Include SAP hana backint role
  include_role:
    name: sap-hana-backint
  when: sap_hana_backint_install|bool == true

- name: Include SAP HANA Fast Restart Role
  include_role:
    name: sap-hana-fast-restart
  when: sap_hana_fast_restart|bool == true
