# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: 'Create {{ sap_hana_sid }} dir in {{ sap_hana_data_mountpoint }} and {{ sap_hana_log_mountpoint }}'
  file:
    path: '{{ item }}'
    state: directory
    recurse: true
    mode: 0775
  with_items:
    - '{{ sap_hana_data_mountpoint }}/{{ sap_hana_sid }}'
    - '{{ sap_hana_log_mountpoint }}/{{ sap_hana_sid }}'

- name: 'Create {{ sap_hana_data_mountpoint }} and {{ sap_hana_log_mountpoint }}'
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ sap_hana_system_uid }}'
    group: '{{ sap_sapsys_gid }}'
    recurse: true
    mode: 0775
  with_items:
    - '{{ sap_hana_data_mountpoint }}'
    - '{{ sap_hana_log_mountpoint }}'

- name: Run /usr/bin/sync
  shell: >
    /usr/bin/sync
  register: sync_run

- name: 'Umount {{ sap_hana_data_mountpoint }} and {{ sap_hana_log_mountpoint }}'
  mount:
    path: '{{ item }}'
    state: unmounted
  with_items:
    - '{{ sap_hana_data_mountpoint }}'
    - '{{ sap_hana_log_mountpoint }}'

- name: 'Create {{ sap_hana_shared_mountpoint }} and {{ sap_hana_backup_mountpoint }}'
  file:
    path: '{{ item }}'
    state: directory
    recurse: true
    mode: 0775
  with_items:
    - '{{ sap_hana_shared_mountpoint }}'
    - '{{ sap_hana_backup_mountpoint }}'

- name: Run /sbin/vgchange
  shell: >
    /sbin/vgchange -a n {{ sap_hana_data_partition_name }}
  register: vg_change_run

- name: 'Mount {{ sap_hana_shared_mountpoint }} and {{ sap_hana_backup_mountpoint }} filestore volumes'
  mount:
    src: '{{ item.source }}'
    path: '{{ item.path }}'
    state: mounted
    fstype: nfs
  loop:
    - { source: '{{ sap_hana_shared_fs_mount_point }}', path: '{{ sap_hana_shared_mountpoint }}' }
    - { source: '{{ sap_hana_backup_fs_mount_point }}', path: '{{ sap_hana_backup_mountpoint }}' }
