# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include storage role
  include_role:
    name: storage
  vars:
    disks: '{{ sap_nw_disks_pas }}'
    logvols: '{{ sap_nw_logvols_pas }}'

- name: include nfs-client role
  include_role:
    name: nfs-client
  vars:
    nfs_client_mounts: '{{ sap_nw_nfsvols_pas }}'
    nfs_client_mode: autofs

- name: include nw-pre role
  include_role:
    name: nw-pre
  vars:
    sap_product_and_version: '{{ sap_nw_product_and_version }}'

- name: include sapinst role for db
  include_role:
    name: sapinst
  vars:
    sap_product_id: '{{ sap_product_vars[sap_nw_product_and_version].db_product_id }}'
    sap_sapinst_state_file: /root/.ansible-state/run-sapinst-db
    sap_sapinst_swpm_path: '{{ sap_product_vars[sap_nw_product_and_version].swpm_path }}'
    sap_sapinst_template: '{{ sap_product_vars[sap_nw_product_and_version].db_sapinst_template | default("inifile_db_hdb.params") }}'

- name: include sapinst role for pas
  include_role:
    name: sapinst
  vars:
    sap_product_id: '{{ sap_product_vars[sap_nw_product_and_version].pas_product_id }}'
    sap_sapinst_state_file: /root/.ansible-state/run-sapinst-pas
    sap_sapinst_swpm_path: '{{ sap_product_vars[sap_nw_product_and_version].swpm_path }}'
    sap_sapinst_template: '{{ sap_product_vars[sap_nw_product_and_version].as_sapinst_template | default("inifile_as_hdb.params") }}'

- name: include sap-hana-hdb-userstore role
  include_role:
    name: sap-hana-hdb-userstore
  vars:
    hdb_us_become_user: '{{ sap_nw_user }}'
    hdb_us_db_host: '{{ sap_hana_virtual_host }}'
    hdb_us_db_name: '{{ sap_nw_db_sid }}'
    hdb_us_db_password: '{{ sap_nw_schema_password }}'
    hdb_us_db_port: '3{{ sap_hana_instance_number }}13'
    hdb_us_db_user: '{{ sap_nw_schema }}'
    hdb_us_key: DEFAULT
    hdb_us_source_file: '/home/{{ sap_nw_user }}/.profile'
